### ISSUE TITLE
[Bug Report]: crash reaction chamber

### ISSUE THREAD

**Issue by lorenzo251110** [pedroksl/AdvancedAE#201]
### Minecraft Version

1.20.1

### Mod Version

1.2.4

### Did you test the latest version?

Yes

### Severity

Crashing

### NeoForge Version

forge: 47.4.0

### Describe the Issue

The game crashes whenever I open the directional output in the reaction chamber.

### Reproduction Steps

In a Creative world with only AE2 and Advanced AE2 installed, placing the Reaction Chamber and clicking on the Directional Output causes the game to crash

### Crash log

https://mclo.gs/TQaOzQi

**Comment by pedroksl** [comment]
This issue is in a similar state to #200, I tried to reproduce the error in dev, but I see no issues here.

<img width="456" height="228" alt="Image" src="https://github.com/user-attachments/assets/68e6d8c3-057f-4fab-b30b-5f5e0351dc61" />

This makes it extremely hard to figure out what could be wrong.

**Comment by pedroksl** [comment]
Using a forge install I was able to reproduce the issue. Which means the problem was because the dev environment deobfuscates everything and just knows some methods it otherwise wouldn't. I have fixed the issue and made a new release containing the fix.

**Comment by BOLTMAGIC** [comment]
I still have this crash.
here a crash report.
https://pastebin.com/G0yNDnqc

**Comment by pedroksl** [comment]
@BOLTMAGIC That issue was fixed in version 1.2.5, you're using 1.2.4. Please update the mod.

**Comment by pedroksl** [comment]
@omeranha I still haven't released version 1.4.3 hahaha
However, are you using a resource pack that changes the UI like AE2 Blackout?
Json errors like that mean the style sheet is incorrect, and I assume it was modified in your client.

**Comment by omeranha** [comment]
@pedroksl ae2blackout was the issue, thanks

<img width="553" height="349" alt="Image" src="https://github.com/user-attachments/assets/cc17025a-7bae-433d-9e3c-ce7ddadde2bc" />
